### ISSUE TITLE
error: TS2345 [ERROR] when install electric

### ISSUE THREAD

**Issue by pitersky** [denjucks/deno-cef#1]
```
deno --version
deno 1.2.0
v8 8.5.216
typescript 3.9.2
```

running `deno install -A -f --unstable https://raw.githubusercontent.com/denjucks/deno-cef/master/electric.js`

got this

```
Check https://raw.githubusercontent.com/denjucks/deno-cef/master/electric.js
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.55.0/path/win32.ts:917:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.55.0/path/posix.ts:438:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@v0.54.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@v0.54.0/path/posix.ts:433:18

Found 4 errors.
```

**Comment by pitersky** [comment]
So i made test.ts with the content
```
"use strict";

import * as path from "https://deno.land/std@0.55.0/path/mod.ts";
```

And got same error after running `deno run test.ts`. It seems its deno std lib issue, not related to deno-cef, closing, sorry.
